### ISSUE TITLE
Summary: Meets Expectations

### ISSUE THREAD

**Issue by zannain** [Hilawol/TeaCozy#5]
Really great work with this mockup. I like that you ran the webpage through a validator and commented the stylesheet and markup which will make collaborating with other developers much easier in a professional setting. Going forward I've listed a few resources below to build on your HTML and CSS foundation with responsive design. This is a critical requirement in every application you will design because the web is being viewed from all sorts of devices ranging from mobiles to 35-inch ultrawide monitors and so you want your webpage to render properly regardless of the viewport the end user is viewing it from. Keep up the **awesome work!!**

[CSS Grid Course](https://www.codecademy.com/courses/learn-css-grid/lessons/css-grid-i/exercises/grid-intro?course_redirect=learn-css)
[CSS Grids](https://cssgrid.io/)
[CSSGridGarden game](https://cssgridgarden.com/)

**Comment by Hilawol** [comment]
Thank you for your comments and links to all the resources. 
Hila
